// Generated by scripts/generate-counter-aliases.js; do not edit.
export default {
  "大白": {
    "code": "greegr",
    "name": "大白鷺"
  },
  "大白鷺": {
    "code": "greegr",
    "name": "大白鷺"
  },
  "蒼鷺": {
    "code": "graher1",
    "name": "蒼鷺"
  },
  "原鴿": {
    "code": "rocpig1",
    "codes": [
      "rocpig1",
      "rocpig"
    ],
    "name": "野鴿"
  },
  "野鴿(馴化)": {
    "code": "rocpig1",
    "codes": [
      "rocpig1",
      "rocpig"
    ],
    "name": "野鴿"
  },
  "野鴿(野化)": {
    "code": "rocpig1",
    "codes": [
      "rocpig1",
      "rocpig"
    ],
    "name": "野鴿"
  },
  "金背": {
    "code": "ortdov",
    "name": "金背鳩"
  },
  "金背鳩": {
    "code": "ortdov",
    "name": "金背鳩"
  },
  "珠頸": {
    "code": "spodov",
    "name": "珠頸斑鳩"
  },
  "珠頸斑鳩": {
    "code": "spodov",
    "name": "珠頸斑鳩"
  },
  "紅鳩": {
    "code": "recdov1",
    "name": "紅鳩"
  },
  "野鴿": {
    "code": "rocpig1",
    "codes": [
      "rocpig1",
      "rocpig"
    ],
    "name": "野鴿"
  },
  "紅嘴": {
    "code": "blabul1",
    "name": "紅嘴黑鵯"
  },
  "紅嘴黑鵯": {
    "code": "blabul1",
    "name": "紅嘴黑鵯"
  },
  "小雨燕": {
    "code": "houswi1",
    "codes": [
      "houswi1",
      "houswi"
    ],
    "name": "小雨燕"
  },
  "紅冠": {
    "code": "commoo3",
    "name": "紅冠水雞"
  },
  "紅冠水雞": {
    "code": "commoo3",
    "name": "紅冠水雞"
  },
  "小環": {
    "code": "lirplo",
    "name": "小環頸鴴"
  },
  "小環頸鴴": {
    "code": "lirplo",
    "name": "小環頸鴴"
  },
  "磯鷸": {
    "code": "comsan",
    "name": "磯鷸"
  },
  "白腰": {
    "code": "grnsan",
    "name": "白腰草鷸"
  },
  "白腰鵲鴝": {
    "code": "whrsha",
    "name": "白腰鵲鴝"
  },
  "白腰草鷸": {
    "code": "grnsan",
    "name": "白腰草鷸"
  },
  "夜鷺": {
    "code": "bcnher",
    "name": "夜鷺"
  },
  "白腹": {
    "code": "whbwat1",
    "name": "白腹秧雞"
  },
  "白腹秧雞": {
    "code": "whbwat1",
    "name": "白腹秧雞"
  },
  "小白": {
    "code": "litegr",
    "name": "小白鷺"
  },
  "小白鷺": {
    "code": "litegr",
    "name": "小白鷺"
  },
  "黃頭鷺": {
    "code": "categr2",
    "name": "黃頭鷺"
  },
  "喜鵲": {
    "code": "orimag1",
    "name": "喜鵲"
  },
  "台灣藍鵲": {
    "code": "formag1",
    "name": "臺灣藍鵲"
  },
  "臺灣藍鵲": {
    "code": "formag1",
    "name": "臺灣藍鵲"
  },
  "黑冠": {
    "code": "manher1",
    "name": "黑冠麻鷺"
  },
  "黑冠麻鷺": {
    "code": "manher1",
    "name": "黑冠麻鷺"
  },
  "樹鵲": {
    "code": "grytre1",
    "name": "樹鵲"
  },
  "東方": {
    "code": "kenplo1",
    "name": "東方環頸鴴"
  },
  "東方環頸鴴": {
    "code": "kenplo1",
    "name": "東方環頸鴴"
  },
  "花嘴": {
    "code": "spbduc",
    "name": "花嘴鴨"
  },
  "花嘴鴨": {
    "code": "spbduc",
    "name": "花嘴鴨"
  },
  "東方黃": {
    "code": "weywag8",
    "name": "東方黃鶺鴒(黃眉)"
  },
  "東方黃鶺鴒(黃眉)": {
    "code": "weywag8",
    "name": "東方黃鶺鴒(黃眉)"
  },
  "東方黃鶺鴒": {
    "code": "eaywag",
    "name": "東方黃鶺鴒"
  },
  "大卷尾": {
    "code": "bladro1",
    "name": "大卷尾"
  },
  "五色鳥": {
    "code": "taibar2",
    "name": "五色鳥"
  },
  "亞洲": {
    "code": "asgsta1",
    "name": "亞洲輝椋鳥"
  },
  "亞洲輝椋鳥": {
    "code": "asgsta1",
    "name": "亞洲輝椋鳥"
  },
  "褐頭": {
    "code": "plapri1",
    "name": "褐頭鷦鶯"
  },
  "褐頭鷦鶯": {
    "code": "plapri1",
    "name": "褐頭鷦鶯"
  },
  "灰頭鷦鶯": {
    "code": "yebpri1",
    "codes": [
      "yebpri1",
      "gybpri1"
    ],
    "name": "灰頭鷦鶯"
  },
  "翠鳥": {
    "code": "comkin1",
    "name": "翠鳥"
  },
  "斑馬鳩": {
    "code": "zebdov",
    "name": "斑馬鳩"
  },
  "家燕": {
    "code": "barswa",
    "name": "家燕"
  },
  "洋燕": {
    "code": "pacswa1",
    "name": "洋燕"
  },
  "赤腰燕": {
    "code": "strswa2",
    "codes": [
      "strswa2",
      "y00621",
      "strswa1"
    ],
    "name": "東方金腰燕 (赤腰燕)"
  },
  "東方金腰燕": {
    "code": "strswa2",
    "codes": [
      "strswa2",
      "y00621",
      "strswa1"
    ],
    "name": "東方金腰燕 (赤腰燕)"
  },
  "白頭翁": {
    "code": "livbul1",
    "name": "白頭翁"
  },
  "斯氏": {
    "code": "swiwhe1",
    "name": "斯氏繡眼"
  },
  "斯氏繡眼": {
    "code": "swiwhe1",
    "name": "斯氏繡眼"
  },
  "黑領": {
    "code": "bkcsta1",
    "name": "黑領椋鳥"
  },
  "黑領椋鳥": {
    "code": "bkcsta1",
    "name": "黑領椋鳥"
  },
  "家八": {
    "code": "commyn",
    "name": "家八哥"
  },
  "家八哥": {
    "code": "commyn",
    "name": "家八哥"
  },
  "冠八": {
    "code": "cremyn",
    "name": "八哥 (冠八哥)"
  },
  "八哥 (冠八哥)": {
    "code": "cremyn",
    "name": "八哥 (冠八哥)"
  },
  "八哥(冠八哥)": {
    "code": "cremyn",
    "name": "八哥 (冠八哥)"
  },
  "白尾": {
    "code": "whvmyn",
    "name": "白尾八哥"
  },
  "白尾八哥": {
    "code": "whvmyn",
    "name": "白尾八哥"
  },
  "鵲鴝": {
    "code": "magrob",
    "name": "鵲鴝"
  },
  "麻雀": {
    "code": "eutspa",
    "name": "麻雀"
  },
  "斑文鳥": {
    "code": "nutman",
    "name": "斑文鳥"
  },
  "黑頭文鳥": {
    "code": "chemun",
    "name": "黑頭文鳥"
  },
  "葡萄胸": {
    "code": "vibsta4",
    "name": "葡萄胸椋鳥"
  },
  "葡萄胸椋鳥": {
    "code": "vibsta4",
    "name": "葡萄胸椋鳥"
  },
  "灰頭椋鳥": {
    "code": "chtsta2",
    "name": "灰頭椋鳥"
  },
  "綠簑鷺": {
    "code": "strher1",
    "codes": [
      "strher1",
      "strher"
    ],
    "name": "綠簑鷺"
  },
  "小啄木": {
    "code": "gycwoo1",
    "name": "小啄木"
  },
  "薑母鴨": {
    "code": "musduc",
    "codes": [
      "musduc",
      "musduc3",
      "musduc2"
    ],
    "name": "疣鼻棲鴨"
  },
  "疣鼻棲鴨": {
    "code": "musduc",
    "codes": [
      "musduc",
      "musduc3",
      "musduc2"
    ],
    "name": "疣鼻棲鴨"
  },
  "灰鶺鴒": {
    "code": "grywag",
    "name": "灰鶺鴒"
  },
  "紅尾伯勞": {
    "code": "brnshr",
    "name": "紅尾伯勞"
  },
  "紅尾伯勞(灰頭)": {
    "code": "brnshr3",
    "name": "紅尾伯勞(灰頭)"
  },
  "紅尾伯勞(褐頭)": {
    "code": "brnshr1",
    "name": "紅尾伯勞(褐頭)"
  },
  "灰頭紅尾伯勞": {
    "code": "brnshr3",
    "name": "紅尾伯勞(灰頭)"
  },
  "褐頭紅尾伯勞": {
    "code": "brnshr1",
    "name": "紅尾伯勞(褐頭)"
  },
  "白面": {
    "code": "whiwag8",
    "name": "白鶺鴒（白面）"
  },
  "白鶺鴒（白面）": {
    "code": "whiwag8",
    "name": "白鶺鴒（白面）"
  }
};
